global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - auth-service:8081
          - price-processor:8080
